casetteadmin/casetteadmin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
import casetteadmin.settings as settings

urlpatterns = [
    #admin
    url(r'^admin/', admin.site.urls),
    #customerService
    url(r'^customer/', include('customerService.urls')),
    #mediaService
    url(r'^stock/', include('mediaService.urls')),
    #rentService
    url(r'^rent/', include('rentService.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

casetteadmin/customerService/urls.py
from django.conf.urls import url

from . import views

app_name = 'customer'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^insertcustomer$', views.insert_customer, name='insertcustomer'),
    url(r'^editcustomer/(?P<customer_id>[0-9]+)/$', views.edit_customer, name='editcustomer'),
    url(r'^updatecustomer/(?P<customer_id>[0-9]+)/$', views.update_customer, name='updatecustomer'),
    url(r'^searchcustomer$', views.search_customer, name='searchcustomer'),
    url(r'^deletecustomer/(?P<customer_id>[0-9]+)/$', views.delete_customer, name='deletecustomer'),
    url(r'^customerdatasheet/(?P<customer_id>[0-9]+)/$', views.customer_sheet, name='customerdatasheet'),
    url(r'^rentmedia/(?P<customer_id>[0-9]+)/$', views.rent_media, name='rentmedia'),
    url(r'^unrentmedia/(?P<customer_id>[0-9]+)/(?P<media_id>[0-9]+)/(?P<from_site>[a-z]+)/$', views.unrent_media, name='unrentmedia'),
]

casetteadmin/mediaService/urls.py
from django.conf.urls import url

from . import views

app_name = 'media'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^insertmedia$', views.insert_media, name='insertmedia'),
    url(r'^editmedia/(?P<media_id>[0-9]+)/$', views.edit_media, name='editmedia'),
    url(r'^updatemedia/(?P<media_id>[0-9]+)/$', views.update_media, name='updatemedia'),
    url(r'^deletemedia/(?P<media_id>[0-9]+)/$', views.delete_media, name='deletemedia'),
    url(r'^mediadatasheet/(?P<media_id>[0-9]+)/$', views.media_sheet, name='mediadatasheet'),
]

casetteadmin/rentService/urls.py
from django.conf.urls import url

from . import views

app_name = 'rent'
urlpatterns = [
    url(r'^(?P<status>[a-z]+)/$', views.index, name='index'),
    url(r'^makerent$', views.make_rent, name='makerent'),
]

casetteadmin/mediaService/models.py
from django.db import models

import typeService.models as Types
import customerService.models as Customers


class Media(models.Model):
    media_title = models.CharField(max_length=200)
    purchase_date = models.DateField()
    rented_date = models.DateField(null=True)
    seq = models.CharField(max_length=20, unique=True)
    media_type = models.OneToOneField(Types.Type, related_name="media_type")
    status_type = models.OneToOneField(Types.Type, related_name="media_status_type")
    is_deleted = models.BooleanField(default=False)
    customer = models.ForeignKey(Customers.Customer, related_name="medias", null=True)

    def __str__(self):
        return self.media_title

casetteadmin/mediaService/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from mediaService.models import Media
from mediaService.data_access import media_data_access as DataAccess
from typeService.data_access import data_access as TypeDataAccess, category_keys as CategoryKeys
from typeService.data_access import type_keys as TypeKeys
import mediaService.templates.template_keys as TemplateKeys

def index(request):
    template = loader.get_template(TemplateKeys.all_media)
    context = {
        'media_list': DataAccess.get_all_media(),
        'media_type_list': TypeDataAccess.get_types_by_category_resource_key(CategoryKeys.media_types_category),
        'media_status_type_list': TypeDataAccess.get_types_by_category_resource_key(CategoryKeys.media_status_types_category),
    }
    return HttpResponse(template.render(context, request))

def insert_media(request):
    media = Media()
    media.media_title = request.POST['media_title']
    media.purchase_date = request.POST['purchase_date']
    media.seq = request.POST['media_seq']
    media.media_type = TypeDataAccess.get_type_by_id(request.POST['media_type'])
    media.status_type = TypeDataAccess.get_type_by_id(request.POST['status_type'])
    DataAccess.insert_media(media)
    return HttpResponseRedirect(reverse('media:index'))

def edit_media(request, media_id):
    template = loader.get_template(TemplateKeys.edit_media)
    context = {
        'media': DataAccess.get_media_by_id(media_id),
        'media_type_list': TypeDataAccess.get_types_by_category_resource_key(CategoryKeys.media_types_category),
        'media_status_type_list': TypeDataAccess.get_types_by_category_resource_key(CategoryKeys.media_status_types_category),
    }
    return HttpResponse(template.render(context, request))

def update_media(request, media_id):
    media = DataAccess.get_media_by_id(media_id)
    media.media_title = request.POST['media_title']
    media.purchase_date = request.POST['purchase_date']
    media.seq = request.POST['media_seq']
    media.media_type = TypeDataAccess.get_type_by_id(request.POST['media_type'])
    media.status_type = TypeDataAccess.get_type_by_id(request.POST['status_type'])
    if media.status_type != TypeDataAccess.get_type_by_resource_key(TypeKeys.rented):
        media.customer = None
    DataAccess.update_media(media)
    template = loader.get_template(TemplateKeys.all_media)
    return HttpResponseRedirect(reverse('media:index'))


def delete_media(request, media_id):
    media = DataAccess.get_media_by_id(media_id)
    DataAccess.delete_media(media)
    return HttpResponseRedirect(reverse('media:index'))

def media_sheet(request, media_id):
    media = DataAccess.get_media_by_id(media_id)
    template = loader.get_template(TemplateKeys.media_data_sheet)
    context = {
        'media': media,
    }
    return HttpResponse(template.render(context, request))

casetteadmin/mediaService/templates/addmedia.html
{% block content %}

<div id="addMedia" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Ügyfél hozzáadása</h4>
            </div>
            <div class="modal-body">
              <form action="{% url 'media:insertmedia' %}" method="post" role="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="media_title">Név</label>
                        <input type="text" name="media_title" id="media_title" class="form-control"/>
                    </div>
                    <div class="form-group">
                        <label for="purchase_date">Beszerzés dátuma</label>
                        <input type="date" name="purchase_date" id="purchase_date" class="form-control"/>
                    </div>
                    <div class="form-group">
                        <label for="media_seq">Sorszám</label>
                        <input type="text" name="media_seq" id="media_seq" class="form-control"/>
                    </div>
                    <div class="form-group">
                        <label for="media_type">Típus</label>
                        <select class="form-control" name="media_type" id="media_type">
                            {% for media_type in media_type_list %}
                                  <option {} value="{{ media_type.id }}">{{ media_type.description}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="status_type">Típus</label>
                        <select class="form-control" name="status_type" id="status_type">
                            {% for media_status_type in media_status_type_list %}
                                  <option value="{{ media_status_type.id }}">{{ media_status_type.description}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-floppy-disk"></span> Mentés</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

casetteadmin/mediaService/templates/editmedia.html
{% extends "header_footer.html" %}
{% block content %}
<div class="container">
    <form action="{% url 'media:updatemedia' media.id%}" method="post" role="form">
        {% csrf_token %}
        <div class="form-group">
            <label for="media_title">Név</label>
            <input type="text" name="media_title" id="media_title" class="form-control" value="{{media.media_title}}"/>
        </div>
        <div class="form-group">
            <label for="purchase_date">Beszerzés dátuma</label>
            <input type="date" name="purchase_date" id="purchase_date" class="form-control" value="{{media.purchase_date | date:"Y-m-d"}}"/>
        </div>
        <div class="form-group">
            <label for="media_seq">Sorszám</label>
            <input type="text" name="media_seq" id="media_seq" class="form-control" value="{{media.seq}}"/>
        </div>
        <div class="form-group">
            <label for="media_type">Típus</label>
            <select class="form-control" name="media_type" id="media_type">
                {% for media_type in media_type_list %}
                      <option {% if media_type == media.media_type %}selected{% endif%} value="{{ media_type.id }}">{{ media_type.description}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="status_type">Típus</label>
            <select class="form-control" name="status_type" id="status_type">
                {% for media_status_type in media_status_type_list %}
                      <option {% if media_status_type == media.status_type %}selected{% endif%}  value="{{ media_status_type.id }}">{{ media_status_type.description}}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span> Mentés</button>
    </form>
</div>
{% endblock %}

casetteadmin/mediaService/templates/mediadatasheet.html
{% extends "header_footer.html" %}
{% block content %}
<div class="container">
    <div class="row"><h1>Adatlap</h1></div>
    <div class="panel panel-default">
        <div class="panel-body">
            <a {% if media.customer != None %}
                    href="{% url 'customer:unrentmedia' media.customer.id media.id 'media'%}"
               {% else %}
                    disabled
               {%endif %} title="Kölcsönzés vége" class="btn btn-default pull-right"><span class="glyphicon glyphicon-share-alt"></span></a>
            <a href="{% url 'media:editmedia' media.id %}" title="Média szerkesztése" class="btn btn-default pull-right"><span class="glyphicon glyphicon-pencil"></span></a>
            <h4>Név: <span class="label label-success">{{ media.media_title }}</span></h4>
            <h4>Beszerzés dátuma: <span class="label label-success">{{ media.purchase_date | date:"Y.m.d." }}</span></h4>
            <h4>Kölcsönzés dátuma: <span class="label label-success">{{ media.rented_date | date:"Y.m.d." }}</span></h4>
            <h4>Sorszám: <span class="label label-success">{{ media.seq }}</span></h4>
            <h4>Típus: <span class="label label-success">{{ media.media_type }}</span></h4>
            <h4>Státusz: <span class="label label-success">{{ media.status_type }}</span></h4>
        </div>
    </div>
</div>
{% endblock %}

casetteadmin/mediaService/templates/stock.html
{% extends "header_footer.html" %}
{% block content %}
{% include "addmedia.html" %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">Készlet
            <a data-toggle="modal" href="#addMedia" class="btn btn-default pull-right"><span class="glyphicon glyphicon-plus"></span></a>
        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Név</th>
                    <th>Beszerzés dátuma</th>
                    <th>Sorszám</th>
                    <th>Típus</th>
                    <th>Státusz</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for media in media_list %}
                <tr ondblclick="document.location = '{% url 'media:mediadatasheet' media.id %}'">
                    <td>{{ media.media_title }}</td>
                    <td>{{ media.purchase_date | date:"Y.m.d." }}</td>
                    <td>{{ media.seq }}</td>
                    <td>{{ media.media_type }}</td>
                    <td>{{ media.status_type }}</td>
                    <td><a href="{% url 'media:deletemedia' media.id %}"><span class="glyphicon glyphicon-trash"></span></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}