casetteadmin/casetteadmin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
import casetteadmin.settings as settings

urlpatterns = [
    #admin
    url(r'^admin/', admin.site.urls),
    #customerService
    url(r'^customer/', include('customerService.urls')),
    #mediaService
    url(r'^stock/', include('mediaService.urls')),
    #rentService
    url(r'^rent/', include('rentService.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

casetteadmin/customerService/urls.py
from django.conf.urls import url

from . import views

app_name = 'customer'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^insertcustomer$', views.insert_customer, name='insertcustomer'),
    url(r'^editcustomer/(?P<customer_id>[0-9]+)/$', views.edit_customer, name='editcustomer'),
    url(r'^updatecustomer/(?P<customer_id>[0-9]+)/$', views.update_customer, name='updatecustomer'),
    url(r'^searchcustomer$', views.search_customer, name='searchcustomer'),
    url(r'^deletecustomer/(?P<customer_id>[0-9]+)/$', views.delete_customer, name='deletecustomer'),
    url(r'^customerdatasheet/(?P<customer_id>[0-9]+)/$', views.customer_sheet, name='customerdatasheet'),
    url(r'^rentmedia/(?P<customer_id>[0-9]+)/$', views.rent_media, name='rentmedia'),
    url(r'^unrentmedia/(?P<customer_id>[0-9]+)/(?P<media_id>[0-9]+)/(?P<from_site>[a-z]+)/$', views.unrent_media, name='unrentmedia'),
]

casetteadmin/mediaService/urls.py
from django.conf.urls import url

from . import views

app_name = 'media'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^insertmedia$', views.insert_media, name='insertmedia'),
    url(r'^editmedia/(?P<media_id>[0-9]+)/$', views.edit_media, name='editmedia'),
    url(r'^updatemedia/(?P<media_id>[0-9]+)/$', views.update_media, name='updatemedia'),
    url(r'^deletemedia/(?P<media_id>[0-9]+)/$', views.delete_media, name='deletemedia'),
    url(r'^mediadatasheet/(?P<media_id>[0-9]+)/$', views.media_sheet, name='mediadatasheet'),
]

casetteadmin/rentService/urls.py
from django.conf.urls import url

from . import views

app_name = 'rent'
urlpatterns = [
    url(r'^(?P<status>[a-z]+)/$', views.index, name='index'),
    url(r'^makerent$', views.make_rent, name='makerent'),
]

casetteadmin/customerService/models.py
from django.db import models

class Customer(models.Model):
    name = models.CharField(max_length=200)
    customer_identifier = models.CharField(max_length=200, unique=True)
    phone_number = models.CharField(max_length=20)
    personal_identifier = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name + ' (' + self.customer_identifier + ')'

casetteadmin/customerService/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.template import loader
import customerService.templates.template_keys as TemplateKeys
import mediaService.templates.template_keys as MediaTemplateKeys
import typeService.data_access.type_keys as TypeKeys
from customerService.models import Customer
import customerService.data_access.customer_data_access as DataAccess
import mediaService.data_access.media_data_access as MediaDataAccess
import typeService.data_access.data_access as TypeDataAccess
from datetime import datetime


def index(request):
    template = loader.get_template(TemplateKeys.all_customer)
    context = {
        'customer_list': DataAccess.get_all_customer(),
    }
    return HttpResponse(template.render(context, request))

def insert_customer(request):
    customer = Customer()
    customer.name = request.POST['name']
    customer.phone_number = request.POST['phone']
    customer.personal_identifier = request.POST['pid']
    customer.address = request.POST['address']
    DataAccess.insert_customer(customer)
    return HttpResponseRedirect(reverse('customer:index'))

def edit_customer(request, customer_id):
    template = loader.get_template(TemplateKeys.edit_customer)
    context = {
        'customer': DataAccess.get_customer_by_id(customer_id),
    }
    return HttpResponse(template.render(context, request))

def update_customer(request, customer_id):
    customer = DataAccess.get_customer_by_id(customer_id)
    customer.name = request.POST['name']
    customer.phone_number = request.POST['phone']
    customer.personal_identifier = request.POST['pid']
    customer.address = request.POST['address']
    DataAccess.update_customer(customer)
    return HttpResponseRedirect(reverse('customer:index'))

def search_customer(request):
    name = request.POST['name']
    customer_identifier = request.POST['customer_identifier']
    personal_identifier = request.POST['pid']
    result = DataAccess.get_customer_by_name_and_customer_identifier_and_personal_identifier(name,customer_identifier, personal_identifier)

    template = loader.get_template(TemplateKeys.all_customer)
    context = {
        'customer_list': result,
    }
    return HttpResponse(template.render(context, request))

def delete_customer(request, customer_id):
    customer = DataAccess.get_customer_by_id(customer_id)
    DataAccess.delete_customer(customer)
    return HttpResponseRedirect(reverse('customer:index'))

def customer_sheet(request, customer_id):
    customer = DataAccess.get_customer_by_id(customer_id)
    template = loader.get_template(TemplateKeys.customer_data_sheet)
    context = {
        'customer': customer,
        'rentable_media': MediaDataAccess.get_all_media().filter(status_type_id = TypeDataAccess.get_type_by_resource_key(TypeKeys.rentable))
    }
    return HttpResponse(template.render(context, request))

def rent_media(request, customer_id):
    media_id = request.POST['media']
    customer = DataAccess.get_customer_by_id(customer_id)
    media = MediaDataAccess.get_media_by_id(media_id)
    media.status_type = TypeDataAccess.get_type_by_resource_key(TypeKeys.rented)
    media.rented_date = datetime.now()
    MediaDataAccess.update_media(media)
    customer.medias.add(media)
    template = loader.get_template(TemplateKeys.customer_data_sheet)
    return HttpResponseRedirect(reverse('customer:customerdatasheet', kwargs={'customer_id':customer_id}))

def unrent_media(request, customer_id, media_id, from_site):
    customer = DataAccess.get_customer_by_id(customer_id)
    media = customer.medias.get(id=media_id)
    media.status_type = TypeDataAccess.get_type_by_resource_key(TypeKeys.rentable)
    media.rented_date = None
    MediaDataAccess.update_media(media)
    customer.medias.remove(media)
    if from_site == "media":
        template = loader.get_template(MediaTemplateKeys.all_media)
        return HttpResponseRedirect(reverse('media:index'))
    else:
        template = loader.get_template(TemplateKeys.customer_data_sheet)
        return HttpResponseRedirect(reverse('customer:customerdatasheet', kwargs={'customer_id':customer_id}))

casetteadmin/customerService/templates/addcustomer.html
{% block content %}

<div id="addCustomer" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Ügyfél hozzáadása</h4>
            </div>
            <div class="modal-body">
              <form action="{% url 'customer:insertcustomer' %}" method="post" role="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">Név</label>
                        <input type="text" name="name" id="name" class="form-control"/>
                    </div>
                    <div class="form-group">
                        <label for="phone">Telefonszám</label>
                        <input type="text" name="phone" id="phone" class="form-control"/>
                    </div>
                    <div class="form-group">
                        <label for="pid">Személyi igazolvány száma</label>
                        <input type="text" name="pid" id="pid" class="form-control"/>
                    </div>
                    <div class="form-group">
                        <label for="address">Cím</label>
                        <input type="text" name="address" id="address" class="form-control"/>
                    </div>
                    <button id="save_customer" type="submit" class="btn btn-default"><span class="glyphicon glyphicon-floppy-disk"></span> Mentés</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

casetteadmin/customerService/templates/customerdatasheet.html
{% extends "header_footer.html" %}
{% block content %}
{% include "rentmedia.html" %}
<div class="container">
    <div class="row"><h1>Adatlap</h1></div>
    <div class="panel panel-default">
        <div class="panel-body">
            <a href="{% url 'customer:editcustomer' customer.id %}" class="btn btn-default pull-right"><span class="glyphicon glyphicon-pencil"></span></a>
            <h4>Név: <span class="label label-success">{{customer.name}}</span></h4>
            <h4>Azonosító: <span class="label label-success">{{customer.customer_identifier}}</span></h4>
            <h4>Telefonszám: <span class="label label-success">{{customer.phone_number}}</span></h4>
            <h4>Személyi igazolvány száma: <span class="label label-success">{{customer.personal_identifier}}</span></h4>
            <h4>Cím: <span class="label label-success">{{customer.address}}</span></h4>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">Kikölcsönzött médiák
            <a data-toggle="modal" {% if rentable_media.count == 0 %}disabled{% else %}href="#rentMedia"{% endif %} class="btn btn-default pull-right"><span class="glyphicon glyphicon-plus"></span></a>
        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Név</th>
                    <th>Beszerzés dátuma</th>
                    <th>Kölcsönzés dátuma</th>
                    <th>Sorszám</th>
                    <th>Típus</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for media in customer.medias.all %}
                <tr ondblclick="document.location = '{% url 'media:mediadatasheet' media.id %}'">
                    <td>{{ media.media_title }}</td>
                    <td>{{ media.purchase_date | date:"Y.m.d." }}</td>
                    <td>{{ media.rented_date | date:"Y.m.d." }}</td>
                    <td>{{ media.seq }}</td>
                    <td>{{ media.media_type }}</td>
                    <td><a href="{% url 'customer:unrentmedia' customer.id media.id 'customer'%}"><span class="glyphicon glyphicon-share-alt"></span></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

casetteadmin/customerService/templates/customers.html
{% extends "header_footer.html" %}
{% block content %}
{% include "addcustomer.html" %}
{% include "searchcustomer.html" %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">Ügyfelek
            <a id="add_customer" data-toggle="modal" href="#addCustomer" class="btn btn-default pull-right"><span class="glyphicon glyphicon-plus"></span></a>
            <a data-toggle="modal" href="#searchCustomer" class="btn btn-default pull-right"><span class="glyphicon glyphicon-search"></span></a>
        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Név</th>
                    <th>Azonosító</th>
                    <th>Személyi szám</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for customer in customer_list %}
                <tr ondblclick="document.location = '{% url 'customer:customerdatasheet' customer.id %}'">
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.customer_identifier }}</td>
                    <td>{{ customer.personal_identifier }}</td>
                    <td><a id="delete_customer_{{customer.id}}" href="{% url 'customer:deletecustomer' customer.id %}"><span class="glyphicon glyphicon-trash"></span></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

casetteadmin/customerService/templates/editcustomer.html
{% extends "header_footer.html" %}
{% block content %}
<div class="container">
    <form action="{% url 'customer:updatecustomer' customer.id%}" method="post" role="form">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">Név</label>
            <input type="text" name="name" id="name" class="form-control" value="{{customer.name}}"/>
        </div>
        <div class="form-group">
            <label for="phone">Telefonszám</label>
            <input type="text" name="phone" id="phone" class="form-control" value="{{customer.phone_number}}"/>
        </div>
        <div class="form-group">
            <label for="pid">Személyi igazolvány száma</label>
            <input type="text" name="pid" id="pid" class="form-control" value="{{customer.personal_identifier}}"/>
        </div>
        <div class="form-group">
            <label for="address">Cím</label>
            <input type="text" name="address" id="address" class="form-control" value="{{customer.address}}"/>
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span> Mentés</button>
    </form>
</div>
{% endblock %}

casetteadmin/customerService/templates/header_footer.html
{% load static %}
<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
<script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Médiakezelő</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="{% if request.path == '/rent/all/' or request.path == '/rent/over/'%}active{% endif%}"><a href="/rent/all/">Kölcsönzés</a></li>
        <li class="{% if request.path == '/customer/' or request.path == '/customer/searchcustomer' or '/customer/customerdatasheet/' in request.path%}active{% endif%}"><a href="/customer/">Ügyfelek</a></li>
        <li class="{% if request.path == '/stock/'  or '/stock/mediadatasheet/' in request.path%}active{% endif%}"><a href="/stock/">Készlet</a></li>
      </ul>
    </div>
  </div>
</nav>
{% block content %}{% endblock %}
<footer class="footer">
    <div class="container">
        <div class="row">
            Czinke Csaba | Copyright 2016
        </div>
    </div>
</footer>
</body>
</html>

casetteadmin/customerService/templates/rentmedia.html
{% block content %}

<div id="rentMedia" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Média kölcsönzés</h4>
            </div>
            <div class="modal-body">
              <form action="{% url 'customer:rentmedia' customer.id %}" method="post" role="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="media">Média</label>
                        <select name="media" id="media" class="form-control">
                        {% for media in rentable_media %}
                          <option value="{{ media.id }}">{{ media.media_title }} | {{ media.seq }}</option>
                        {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-floppy-disk"></span> Mentés</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

casetteadmin/customerService/templates/searchcustomer.html
{% block content %}

<div id="searchCustomer" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Keresés</h4>
            </div>
            <div class="modal-body">
              <form action="{% url 'customer:searchcustomer' %}" method="post" role="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">Név</label>
                        <input type="text" name="name" id="name" class="form-control"/>
                    </div>
                    <div class="form-group">
                        <label for="customer_identifier">Azonosító</label>
                        <input type="text" name="customer_identifier" id="customer_identifier" class="form-control"/>
                    </div>
                    <div class="form-group">
                        <label for="pid">Személyi igazolvány száma</label>
                        <input type="text" name="pid" id="pid" class="form-control"/>
                    </div>
                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Keresés</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}