casetteadmin/casetteadmin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
import casetteadmin.settings as settings

urlpatterns = [
    #admin
    url(r'^admin/', admin.site.urls),
    #customerService
    url(r'^customer/', include('customerService.urls')),
    #mediaService
    url(r'^stock/', include('mediaService.urls')),
    #rentService
    url(r'^rent/', include('rentService.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

casetteadmin/customerService/urls.py
from django.conf.urls import url

from . import views

app_name = 'customer'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^insertcustomer$', views.insert_customer, name='insertcustomer'),
    url(r'^editcustomer/(?P<customer_id>[0-9]+)/$', views.edit_customer, name='editcustomer'),
    url(r'^updatecustomer/(?P<customer_id>[0-9]+)/$', views.update_customer, name='updatecustomer'),
    url(r'^searchcustomer$', views.search_customer, name='searchcustomer'),
    url(r'^deletecustomer/(?P<customer_id>[0-9]+)/$', views.delete_customer, name='deletecustomer'),
    url(r'^customerdatasheet/(?P<customer_id>[0-9]+)/$', views.customer_sheet, name='customerdatasheet'),
    url(r'^rentmedia/(?P<customer_id>[0-9]+)/$', views.rent_media, name='rentmedia'),
    url(r'^unrentmedia/(?P<customer_id>[0-9]+)/(?P<media_id>[0-9]+)/(?P<from_site>[a-z]+)/$', views.unrent_media, name='unrentmedia'),
]

casetteadmin/mediaService/urls.py
from django.conf.urls import url

from . import views

app_name = 'media'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^insertmedia$', views.insert_media, name='insertmedia'),
    url(r'^editmedia/(?P<media_id>[0-9]+)/$', views.edit_media, name='editmedia'),
    url(r'^updatemedia/(?P<media_id>[0-9]+)/$', views.update_media, name='updatemedia'),
    url(r'^deletemedia/(?P<media_id>[0-9]+)/$', views.delete_media, name='deletemedia'),
    url(r'^mediadatasheet/(?P<media_id>[0-9]+)/$', views.media_sheet, name='mediadatasheet'),
]

casetteadmin/rentService/urls.py
from django.conf.urls import url

from . import views

app_name = 'rent'
urlpatterns = [
    url(r'^(?P<status>[a-z]+)/$', views.index, name='index'),
    url(r'^makerent$', views.make_rent, name='makerent'),
]

casetteadmin/rentService/models.py
from django.db import models

# Create your models here.

casetteadmin/rentService/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
import rentService.templates.template_keys as TemplateKeys
import systemSettingService.data_access.system_setting_keys as SystemSettingKeys
import customerService.data_access.customer_data_access as CustomerDataAccess
import mediaService.data_access.media_data_access as MediaDataAccess
import systemSettingService.data_access.system_setting_data_access as SystemSettingDataAccess
from datetime import datetime, timedelta

def index(request, status):
    template = loader.get_template(TemplateKeys.all_rent)
    all_media = MediaDataAccess.get_all_rented_media()
    medias = []
    if status == "all":
        medias = all_media
    else:
        threshold = int(SystemSettingDataAccess.get_system_setting_by_resource_key(SystemSettingKeys.rent_threshold_days).value)
        for media in all_media:
            if media.rented_date != None and media.rented_date + timedelta(threshold) < datetime.now().date():
                medias.append(media)
    context = {
        'media_list': medias
    }
    return HttpResponse(template.render(context, request))

def make_rent(request):
    return HttpResponseRedirect(reverse('rent:index'))

casetteadmin/rentService/templates/makerent.html
{% block content %}

<div id="makeRent" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Kölcsönzési művelet</h4>
            </div>
            <div class="modal-body">
              <table class="table table-striped">
            <thead>
                <tr>
                    <th>Név</th>
                    <th>Kölcsönzött kazetták száma</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for customer in customer_list %}
                <tr>
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.medias.count }}</td>
                    <td><a href="{% url 'customer:customerdatasheet' customer.id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

casetteadmin/rentService/templates/rent.html
{% extends "header_footer.html" %}
{% block content %}
<div class="container">
    <div class="btn-group" role="group">
        <a href="/rent/all/" class="btn btn-default {% if request.path == '/rent/all/' %}active{% else %}{% endif %}">Összes</a>
        <a href="/rent/over/" class="btn btn-default {% if request.path == '/rent/over/' %}active{% else %}{% endif %}">Határidőn túl</a>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">Kölcsönzött médiák</div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Név</th>
                    <th>Kölcsönzés dátuma</th>
                    <th>Sorszám</th>
                    <th>Típus</th>
                    <th>Státusz</th>
                    <th>Kölcsönző</th>
                </tr>
            </thead>
            <tbody>
            {% for media in media_list %}
                <tr ondblclick="document.location = '{% url 'media:mediadatasheet' media.id %}'">
                    <td>{{ media.media_title }}</td>
                    <td>{{ media.rented_date | date:"Y.m.d." }}</td>
                    <td>{{ media.seq }}</td>
                    <td>{{ media.media_type }}</td>
                    <td>{{ media.status_type }}</td>
                    <td>{{ media.customer }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}